export const GET_EVENTS = "GET_EVENTS"
export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS"
export const GET_EVENTS_FAILED = "GET_EVENTS_FAILED"

export const UPDATE_EVENT = "UPDATE_EVENT"
export const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS"
export const UPDATE_EVENT_FAILED = "UPDATE_EVENT_FAILED"

export const UPDATE_LOCAL_EVENTS = "UPDATE_LOCAL_EVENTS"
export const UPDATE_LOCAL_EVENTS_SUCCESS = "UPDATE_LOCAL_EVENTS_SUCCESS"
export const UPDATE_LOCAL_EVENTS_FAILED = "UPDATE_LOCAL_EVENTS_FAILED"