export const GET_INSTRUCTOR_HOURS = "GET_INSTRUCTOR_HOURS"
export const GET_INSTRUCTOR_HOURS_SUCCESS = "GET_INSTRUCTOR_HOURS_SUCCESS"
export const GET_INSTRUCTOR_HOURS_FAILED = "GET_INSTRUCTOR_HOURS_FAILED"

export const GET_INSTRUCTOR_ABSENT_HOURS = "GET_INSTRUCTOR_ABSENT_HOURS"
export const GET_INSTRUCTOR_ABSENT_HOURS_SUCCESS = "GET_INSTRUCTOR_ABSENT_HOURS_SUCCESS"
export const GET_INSTRUCTOR_ABSENT_HOURS_FAILED = "GET_INSTRUCTOR_ABSENT_HOURS_FAILED"

export const GET_INSTRUCTOR_EXAMWISHLIST_COUNT = "GET_INSTRUCTOR_EXAMWISHLIST_COUNT"
export const GET_INSTRUCTOR_EXAMWISHLIST_COUNT_SUCCESS = "GET_INSTRUCTOR_EXAMWISHLIST_COUNT_SUCCESS"
export const GET_INSTRUCTOR_EXAMWISHLIST_COUNT_FAILED = "GET_INSTRUCTOR_EXAMWISHLIST_COUNT_FAILED"

export const GET_VEHICLE_PAYMENTS_STATS = "GET_VEHICLE_PAYMENTS_STATS"
export const GET_VEHICLE_PAYMENTS_STATS_SUCCESS = "GET_VEHICLE_PAYMENTS_STATS_SUCCESS"
export const GET_VEHICLE_PAYMENTS_STATS_FAILED = "GET_VEHICLE_PAYMENTS_STATS_FAILED"

export const GET_INSTRUCTOR_AVG_HOURS = "GET_INSTRUCTOR_AVG_HOURS"
export const GET_INSTRUCTOR_AVG_HOURS_SUCCESS = "GET_INSTRUCTOR_AVG_HOURS_SUCCESS"
export const GET_INSTRUCTOR_AVG_HOURS_FAILED = "GET_INSTRUCTOR_AVG_HOURS_FAILED"