export const GET_PENALTY_TYPES = "GET_PENALTY_TYPES"
export const GET_PENALTY_TYPES_SUCCESS = "GET_PENALTY_TYPES_SUCCESS"
export const GET_PENALTY_TYPES_FAILED = "GET_PENALTY_TYPES_FAILED"

export const GET_PENALTIES = "GET_PENALTIES"
export const GET_PENALTIES_SUCCESS = "GET_PENALTIES_SUCCESS"
export const GET_PENALTIES_FAILED = "GET_PENALTIES_FAILED"

export const CREATE_PENALTY = "CREATE_PENALTY"
export const CREATE_PENALTY_SUCCESS = "CREATE_PENALTY_SUCCESS"
export const CREATE_PENALTY_FAILED = "CREATE_PENALTY_FAILED"

export const UPDATE_PENALTY = "UPDATE_PENALTY"
export const UPDATE_PENALTY_SUCCESS = "UPDATE_PENALTY_SUCCESS"
export const UPDATE_PENALTY_FAILED = "UPDATE_PENALTY_FAILED"