export const GET_REPORT_TYPES = "GET_REPORT_TYPES"
export const GET_REPORT_TYPES_SUCCESS = "GET_REPORT_TYPES_SUCCESS"
export const GET_REPORT_TYPES_FAILED = "GET_REPORT_TYPES_FAILED"

export const GET_REPORTS = "GET_REPORTS"
export const GET_REPORTS_SUCCESS = "GET_REPORTS_SUCCESS"
export const GET_REPORTS_FAILED = "GET_REPORTS_FAILED"

export const CREATE_REPORT = "CREATE_REPORT"
export const CREATE_REPORT_SUCCESS = "CREATE_REPORT_SUCCESS"
export const CREATE_REPORT_FAILED = "CREATE_REPORT_FAILED"

export const UPDATE_REPORT = "UPDATE_REPORT"
export const UPDATE_REPORT_SUCCESS = "UPDATE_REPORT_SUCCESS"
export const UPDATE_REPORT_FAILED = "UPDATE_REPORT_FAILED"