export const CREATE_EXAM_WISHLIST = "CREATE_EXAM_WISHLIST"
export const CREATE_EXAM_WISHLIST_SUCCESS = "CREATE_EXAM_WISHLIST_SUCCESS"
export const CREATE_EXAM_WISHLIST_FAILED = "CREATE_EXAM_WISHLIST_FAILED"