export const GET_VEHICLE = "GET_VEHICLE"
export const GET_VEHICLE_SUCCESS = "GET_VEHICLE_SUCCESS"
export const GET_VEHICLE_FAILED = "GET_VEHICLE_FAILED"

export const GET_VEHICLES = "GET_VEHICLES"
export const GET_VEHICLES_SUCCESS = "GET_VEHICLES_SUCCESS"
export const GET_VEHICLES_FAILED = "GET_VEHICLES_FAILED"